name: Hello Bharat

on:
  push:
    branches: [ "main" ]

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Print Hello Bharat
      run: echo "Hello Bharat"
